import React from 'react'
import styles from '../styles/Home.module.css'
import Head from 'next/head'
import Header from './header'
function Layout({ children }) {
    return (
        <>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                {children}
                <div color='red' > Test</div>
            </main>

        </>
    )
}

export default Layout
